package com.yingzhiyun.yingquxue.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yingzhiyun.yingquxue.OkBean.daobean.CourseSearchBean;
import com.yingzhiyun.yingquxue.OkBean.daobean.SearchHistory;
import com.yingzhiyun.yingquxue.OkBean.daobean.VideoDao;

import com.yingzhiyun.yingquxue.dao.CourseSearchBeanDao;
import com.yingzhiyun.yingquxue.dao.SearchHistoryDao;
import com.yingzhiyun.yingquxue.dao.VideoDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseSearchBeanDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig videoDaoDaoConfig;

    private final CourseSearchBeanDao courseSearchBeanDao;
    private final SearchHistoryDao searchHistoryDao;
    private final VideoDaoDao videoDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseSearchBeanDaoConfig = daoConfigMap.get(CourseSearchBeanDao.class).clone();
        courseSearchBeanDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        videoDaoDaoConfig = daoConfigMap.get(VideoDaoDao.class).clone();
        videoDaoDaoConfig.initIdentityScope(type);

        courseSearchBeanDao = new CourseSearchBeanDao(courseSearchBeanDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        videoDaoDao = new VideoDaoDao(videoDaoDaoConfig, this);

        registerDao(CourseSearchBean.class, courseSearchBeanDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(VideoDao.class, videoDaoDao);
    }
    
    public void clear() {
        courseSearchBeanDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        videoDaoDaoConfig.clearIdentityScope();
    }

    public CourseSearchBeanDao getCourseSearchBeanDao() {
        return courseSearchBeanDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public VideoDaoDao getVideoDaoDao() {
        return videoDaoDao;
    }

}
